borders = "outset"
shadow = false

[colors]
background = "default"
shadow = "blue"
view = "default"
primary = "default"
secondary ="orange"
highlight = "#91C6C2"
highlight_inactive = "#91C6C2"
highlight_text = "orange"
tertiary = "blue"
title_primary = "white"
title_secondary = "yellow"
